{
  "formatVersion": "1.1",
  "component": {
    "group": "systems.comodal",
    "module": "json-iterator",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "5gkm3mujx5dqdiqjpjmh3325mi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-iterator-2.3.12.jar",
          "url": "json-iterator-2.3.12.jar",
          "size": 47346,
          "sha512": "d684cc791cc85d6c185f3e57c209a33b4feecf6d42111ef2b271426831a9b0b8aec6254c436bff1907a40fcfc3e056c1135b32d0af452bcd417db969bd24d666",
          "sha256": "9bdefc0b5450b925d453a8cedfa809167c5cb2e4028dc7f174704f911804652a",
          "sha1": "0762f71a9799f779220a9fcfe1f706c51c46c469",
          "md5": "c3d3e094ba89c23117788b4247118fed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-iterator-2.3.12.jar",
          "url": "json-iterator-2.3.12.jar",
          "size": 47346,
          "sha512": "d684cc791cc85d6c185f3e57c209a33b4feecf6d42111ef2b271426831a9b0b8aec6254c436bff1907a40fcfc3e056c1135b32d0af452bcd417db969bd24d666",
          "sha256": "9bdefc0b5450b925d453a8cedfa809167c5cb2e4028dc7f174704f911804652a",
          "sha1": "0762f71a9799f779220a9fcfe1f706c51c46c469",
          "md5": "c3d3e094ba89c23117788b4247118fed"
        }
      ]
    }
  ]
}
