{
  "formatVersion": "1.1",
  "component": {
    "group": "systems.comodal",
    "module": "json-iterator",
    "version": "2.3.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "etnsjkobl5frlelwhsf7qa4kyi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "json-iterator-2.3.13-SNAPSHOT.jar",
          "url": "json-iterator-2.3.13-SNAPSHOT.jar",
          "size": 47346,
          "sha512": "8a7c27fdf683e771999770f0f1104708bada3db9b41833dd06521deed2379313a2c83abc24099790485adc39cff8a76d1524c5a75afaa147da18cb56eb993ad4",
          "sha256": "5b08acd90c30b174c851f1dfcadb46cd566be8452519caf1e8324fccd86e83d2",
          "sha1": "bbdf4c1e5308802eb0a012c8a978505572a0a693",
          "md5": "bde610ad934a66f43892fe082799d60b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 14,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "json-iterator-2.3.13-SNAPSHOT.jar",
          "url": "json-iterator-2.3.13-SNAPSHOT.jar",
          "size": 47346,
          "sha512": "8a7c27fdf683e771999770f0f1104708bada3db9b41833dd06521deed2379313a2c83abc24099790485adc39cff8a76d1524c5a75afaa147da18cb56eb993ad4",
          "sha256": "5b08acd90c30b174c851f1dfcadb46cd566be8452519caf1e8324fccd86e83d2",
          "sha1": "bbdf4c1e5308802eb0a012c8a978505572a0a693",
          "md5": "bde610ad934a66f43892fe082799d60b"
        }
      ]
    }
  ]
}
